name: test workflow

on:
  push:
    branches:
      - main
      - Manishgupta3239-patch-1

jobs:
  mainjob:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "hello world"

      - name: second step
        run: echo "hello world form mian"
